"""Initial async migration

Revision ID: 3f24022eae1b
Revises: 
Create Date: 2025-04-22 13:16:16.669880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f24022eae1b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game', 'group_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('player_games', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player_games', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.alter_column('game', 'group_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
